### ISSUE TITLE
Docker image URL is incorrect

### ISSUE THREAD

**Issue by iandelahorne** [starkandwayne/bosh2-errand-resource#8]
When I'm trying to use the bosh2-errand-resource in my concourse, I've defined it like in the readme:

```yaml
- name: bosh-errand
  type: docker-image
  source:
    repository: cloudfoundry-community/bosh2-errand-resource
```

This results in the following output from concourse:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 401 Unauthorized
```

It seems the docker image doesn't reside under `cloudfoundry-community`, according to docker either:

```
$ docker pull cloudfoundry-community/bosh2-errand-resource
Using default tag: latest
Error response from daemon: repository cloudfoundry-community/bosh2-errand-resource not found: does not exist or no pull access
``` 

I suspect that `cfcommunity/bosh2-errand-resource` is the correct resource but I have no evidence to back this up.

**Comment by iainsproat** [comment]
@lflux I think your suspicion is correct, it's already [updated to cfcommunity in the pipeline.yaml](https://github.com/cloudfoundry-community/bosh2-errand-resource/blob/master/ci/pipeline.yml#L16)
